title: 7EDM Portfolio of Allek Laquindanum
description: My Final portfolio for 7EDM Midterm Lab Tasks
show_downloads: true
#theme: jekyll-theme-architect
remote_theme: pages-themes/architect@v0.2.0
plugins: jekyll-remote-theme
